Upgraded to latest Python + mkdocs
Hooley dooley! Python's ecosystem never ceases to amaze. Our
Python version locked, dependency locked, virtual environment
build was no longer reproducible and was failing for new
installations.

Perhaps more impressive. After upgrading, the Python markdown
package was encountering the error:

> AssertionError: we should not get here!

in the Python html package. https://github.com/mkdocs/mkdocs/issues/4001
Quality all around.